import {jsonp,toast,initTheme,initMobileNav} from './api.js';
initTheme();initMobileNav();
const result=document.getElementById('result'),mapel=document.getElementById('mapel'),count=document.getElementById('student-count'),last=document.getElementById('last-name');
let students=[],scanner,processing=false,lastCode='',lastTime=0;
const show=(msg,type='info')=>{result.textContent=msg;result.className='result '+type};
async function loadStudents(){try{const r=await jsonp({action:'students'});students=r.students||[];count.textContent=students.length;show(students.length?'Kamera siap. Mapel: '+mapel.value+'.':'Belum ada siswa di database.','info');return !!students.length}catch(e){show(e.message,'error');return false}}
async function send(student){try{const r=await jsonp({action:'attendance',nis:student.nis,nama:student.nama,kelas:student.kelas,mapel:mapel.value,qr:student.qr});last.textContent=student.nama;if(r.duplicate){show(r.message,'warning');toast(r.message,'warning')}else{show(r.message,'success');toast(r.message,'success')}}catch(e){show(e.message,'error');toast(e.message,'error')}finally{processing=false}}
function handle(decoded){if(processing||!decoded)return;const code=decoded.trim().toUpperCase(),now=Date.now();if(code===lastCode&&now-lastTime<4000)return;lastCode=code;lastTime=now;const student=students.find(s=>String(s.qr).trim().toUpperCase()===code);if(!student){show('QR tidak valid atau siswa tidak terdaftar.','error');toast('QR tidak dikenali.','error');setTimeout(()=>{lastCode=''},1500);return}processing=true;show('Memproses '+student.nama+'...','info');send(student)}
async function start(){if(!(await loadStudents()))return;scanner=new Html5Qrcode('reader');try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},handle,()=>{});show('Kamera aktif. Arahkan QR ke kotak scanner.','info')}catch(e){show('Kamera tidak dapat diakses. Izinkan kamera dan gunakan HTTPS/localhost.','error')}}
mapel.onchange=()=>{lastCode='';show('Mapel dipilih: '+mapel.value+'. Silakan scan.','info')};
document.getElementById('reset').onclick=async()=>{try{if(scanner)await scanner.stop()}catch(e){}location.reload()};start();